import { McpServer } from "@modelcontextprotocol/sdk/server/mcp";

import { z } from "zod";
import { OverpassElement, OverpassResponse, Place } from "../types/tourism-overpass";

/**
 * 
 */

const OVERPASS_API='https://overpass-api.de/api/interpreter';


export function registerTourismTools(mcpServer: McpServer) {
    
    mcpServer.registerTool(
        "get_tourist_attractions",
        {
            description: "Get nearby tourist attractions, cafes, and restaurants for the given latitude & longitude",
            inputSchema: z.object({
                latitude: z.number().describe("The latitude of the location"),
                longitude: z.number().describe("The longitude of the location"),
                radius: z.number().describe("The radius in meters to search for attractions"),
            })
        },
        async({latitude,longitude,radius}) => {
            
            const elements = await getNearbyTouristAttractions(latitude,longitude,radius);
            const touristAttractions = mapOverpassElementResponseToPlace(elements);

            return { 
                content: [
                    {
                        type: "text",
                        text: JSON.stringify({
                            touristAttractions: touristAttractions,
                        })
                    },
                ],
            };
        }
    );
}

/**
 * Get the list of tourist attractions, cafe & restaurants within a given radius of the specified latitude & longitude using the Overpass API.
 * 
 * @param latitude 
 * @param longitude 
 * @param radius 
 * @returns 
 */
async function getNearbyTouristAttractions(latitude: number, longitude: number, radius: number): Promise<OverpassElement[] | null> {
    
    /**
     * These defintions were generated with the help of AI
     * 
     * nodes - A single geographic point with an exact latitude and longitude | Small points of interest, street lamps, small statues, individual trees, or a specific shop entrance.
     * way - An ordered list of nodes connected together. It can form a line (a street or river) or close into a polygon (a building footprint, park, or lake).
     * relation - A container that bundles multiple nodes, ways, or other relations together to show how they interact | A massive complex like the Palace of Versailles, a multi-building university campus, a long-distance bicycle route, or a large national park.
     */
    const query = `
        [out:json][timeout:25];
        (
        node["amenity"="restaurant"](around:${radius},${latitude},${longitude});
        node["amenity"="cafe"](around:${radius},${latitude},${longitude});
        node["tourism"~"attraction|museum|viewpoint"](around:${radius},${latitude},${longitude});
        way["amenity"="restaurant"](around:${radius},${latitude},${longitude});
        way["amenity"="cafe"](around:${radius},${latitude},${longitude});
        way["tourism"~"attraction|museum|viewpoint"](around:${radius},${latitude},${longitude});
        relation["tourism"~"attraction|museum|viewpoint"](around:${radius},${latitude},${longitude});
        );
        out center 15;
    `.trim();

    console.error(`Overpass Query : ${query}`);

    try {
        const response = await fetch(OVERPASS_API, {
            method: 'POST',
            // Overpass expects application/x-www-form-urlencoded format for POST bodies
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'Accept': 'application/json',
                'User-Agent': 'McpTourismServer/1.0 (https://github.com/umeshkumark/gen-ai; contact: umeshkumark@outlook.com)'
            },
            // Pass the data prefix in the body payload
            body: `data=${encodeURIComponent(query)}`,
        });

        console.error(`Overpass API response : ${response}`);

        if (!response.ok) {
            // Grab text error if available to help debug
            const errorText = await response.text().catch(() => '');
            throw new Error(`Overpass API error: ${response.status} ${response.statusText}. Details: ${errorText}`);
        }

        const data: OverpassResponse = await response.json();
        return data.elements; 
    } catch (error) {
        console.error('Failed to fetch from Overpass:', error);
        throw error;
    }
    
}


/***
 * Code generated by AI tool
 */
function mapOverpassElementResponseToPlace(elements: OverpassElement[] | null | undefined): Place[] {

    console.error(`elements received for mapping : ${elements?.length}`);

    if (!elements || !Array.isArray(elements)) return [];

    const mapped = elements.map((el): Place | null => {
        const tags = el.tags || {};
        
        // 1. Resolve coordinates safely. 
        // Nodes use el.lat/lon. Ways use el.lat/lon when 'out center;' is appended to query.
        const lat = el.lat;
        const lon = el.lon;
        
        // If an element lacks coordinate telemetry, discard it in the next filtering phase
        if (lat === undefined || lon === undefined) return null;

        // 2. Identify and categorise the primary type
        let primaryType: Place['type'] = 'unknown';
        if (tags.amenity === 'restaurant') primaryType = 'restaurant';
        else if (tags.amenity === 'cafe') primaryType = 'cafe';
        else if (tags.tourism) primaryType = 'attraction';

        // 3. Assemble full address from separate string keys safely
        const street = tags['addr:street'];
        const houseNumber = tags['addr:housenumber'];
        const city = tags['addr:city'];
        
        let fullAddress: string | undefined;
        if (street) {
            fullAddress = houseNumber ? `${houseNumber} ${street}` : street;
            if (city) fullAddress += `, ${city}`;
        }

        // 4. Return the cleaned object mapping
        return {
            id: `${el.type}-${el.id}`, // Guaranteed unique even if node & way share IDs
            name: tags.name || tags['name:en'] || `Unnamed ${primaryType}`,
            type: primaryType,
            lat: lat,
            lon: lon,
            cuisine: tags.cuisine,
            website: tags.website,
            openingHours: tags.opening_hours,
            address: fullAddress,
            rawTags: tags
        };
    });

    // 5. Filter out elements that were skipped due to missing geometry data
    return mapped.filter((item): item is Place => item !== null);
}

